### ISSUE TITLE
[bug] Auth command not work on macos?

### ISSUE THREAD

**Issue by towry** [jcdickinson/codeium.nvim#1]
https://superuser.com/questions/911735/how-do-i-use-xdg-open-from-xdg-utils-on-mac-osx

> xdg-open is pretty neatly tied into the freedeskop environments, and OSX' counterpart would be the open command.

**Comment by jcdickinson** [comment]
I have fixed this and checked it on my work M1. Please let me know if it works for you also.

**Comment by towry** [comment]
fixed.
