### ISSUE TITLE
Required options and documentation

### ISSUE THREAD

**Issue by zeitchef** [jcdickinson/codeium.nvim#11]
Wondering if there are other arguments `:Codeium` expects? I was expecting to see something like `:Codeium Status` to confirm everything was ok, but found no documentation.

**Comment by jcdickinson** [comment]
None of the options are required, except for the nvim-cmp setup. This plugin is still a WIP, so there is no healthcheck yet. It will create a log at `~/.cache/nvim/codeium.log`. Is it not working for you?

**Comment by jcdickinson** [comment]
If you are still having issues, I have added more troubleshooting options:

https://github.com/jcdickinson/codeium.nvim#troubleshooting
