### ISSUE TITLE
Duplicate suggestion text in the doc window

### ISSUE THREAD

**Issue by naquad** [jcdickinson/codeium.nvim#16]
While trying out codeium.nvim I've noted the following:

![image](https://user-images.githubusercontent.com/20373/215733141-51e04354-e5e3-46be-8b04-d3f9c1f743ea.png)

The suggested multiline text in the documentation window is duplicated. It has been reproduced in other file types too:

![image](https://user-images.githubusercontent.com/20373/215733520-ec909415-4f05-49ea-bf04-8db7fe8da6fd.png)

Any other completion plugin has not exposed such behavior.

Is this a bug or by design?

**Comment by jcdickinson** [comment]
This is a bug. The problem is that my complete setup was truncating anything after a newline on my config. Are your dotfiles up anywhere so that I can refer to them for testing?

**Comment by naquad** [comment]
My dotfiles are 2.5k+ SLOC of Lua with a direct port of the old VIM config. So, no, I'm way too embarrassed to post that anywhere :man_facepalming:

**Comment by CroPhYPtic** [comment]
I'm having the same issue. Even if I'm removing every plugin that I have except planery, cmp and nui I'm still getting duplicates of the documentation. My plugin manager is paq.

All i have in my cmp setup file is: 
```
   mapping = cmp.mapping.preset.insert({    
       ['<C-d>'] = cmp.mapping.scroll_docs(-4),    
       ['<C-f>'] = cmp.mapping.scroll_docs(4),    
       ['<C-c>'] = cmp.mapping.abort(),    
       ['<C-CR>'] = cmp.mapping.confirm({ select = true }),    
       -- ['<C-space>'] = cmp.mapping.confirm {    
       --     behavior = cmp.ConfirmBehavior.Replace,    
       --     select = true,    
       -- },    
       ['<C-e>'] = cmp.mapping(function(fallback)    
           if luasnip.expand_or_jumpable() then    
               luasnip.expand_or_jump()    
           else    
               fallback()    
           end    
       end, { 'i', 's' }),    
   }),

    sources = {    
        { name = "codeium" },
    }
```

and I tried to comment out the whole init.lua file except the loading of the abeove mentioned plugins. Sadly, I don't have my anywhere.

**Comment by jcdickinson** [comment]
I have pushed a commit that removes one of the props from the completion entry, although I still haven't been able to get mine to look like yours. What is your completeopt set to?

**Comment by naquad** [comment]
I've updated the plugin. Great success!

![image](https://user-images.githubusercontent.com/20373/216310375-1878bc54-6c2e-4f72-90a7-914c9021bd8f.png)

Thank you :)
