### ISSUE TITLE
Fail to unpack Language Server

### ISSUE THREAD

**Issue by chrisgrieser** [jcdickinson/codeium.nvim#2]
<img width="1570" alt="Pasted image 2023-01-29 14 46 20" src="https://user-images.githubusercontent.com/73286100/215330337-84156f23-0195-4e18-a528-6ee8bf1c77cc.png">

```
macOS 13.0.1 (M1)
neovim 0.8.2 (homebrew)
```

**Comment by towry** [comment]
```
file language_server_mac_x64.gz
language_server_mac_x64.gz: ASCII text, with no line terminators
```

maybe it's not a gzip file?

**Comment by jcdickinson** [comment]
Also fixed on my work M1. Please check if you works for you all.

**Comment by towry** [comment]
fixed.

**Comment by chrisgrieser** [comment]
can also confirm that the issue is now fixed
