### ISSUE TITLE
Setting symbol for Codeium completion

### ISSUE THREAD

**Issue by DieracDelta** [jcdickinson/codeium.nvim#23]
I see [here](https://gitlab.com/search?search=symbol_map&nav_source=navbar&project_id=36836907&search_code=true&repository_ref=main) the symbol_map for nvim_cmp is set with one mapping: `Suggestion`. Does `Suggestion` correspond only to codeium's suggestions?

**Comment by jcdickinson** [comment]
Yes, I haven't seen any other suggestion plugins use this. If you have a better category then I am open to changing it.

**Comment by DieracDelta** [comment]
Ah, it's set [here](https://github.com/jcdickinson/codeium.nvim/blob/c0a0bd5aba96ad654bd1fd5f90505daed2b356a5/lua/codeium/source.lua#L23). Copilot uses `Copilot`. Maybe `Codeium` would be more specific? And adding some documentation about setting the nvim-cmp icon.

If that sounds good, I can open a PR

**Comment by jcdickinson** [comment]
A PR would be extremely appreciated, thank you!
