### ISSUE TITLE
Completion prefix removed

### ISSUE THREAD

**Issue by naquad** [jcdickinson/codeium.nvim#24]
**Versions**
Codeium: 1.1.32
NeoVIM: v0.8.3
LuaJIT 2.1.0-beta3
nvim-cmp: latest

**Description**

Trying to navigate suggestion options yields unexpected behavior.

**Actual result**

When trying to select (not confirm!) the suggestion it truncates the string prefixing the completion.
Demo:
https://asciinema.org/a/DkoW93CTZk2IFYkjAzaAgpmsZ

**Expected behavior**

Navigating through the suggestions w/o affecting the prefix.

**Notes**

The same configuration works as expected with other sources (LSP, LuaSnip, ...).

**Comment by jcdickinson** [comment]
This should be fixed with the commit I just pushed. Please test and let me know :)

**Comment by naquad** [comment]
Works great! Thank you :)
