### ISSUE TITLE
remove nui dependency?

### ISSUE THREAD

**Issue by chrisgrieser** [jcdickinson/codeium.nvim#27]
as far as I can tell, `nui` is only needed for authentication, isn't it? I tried removing it and everything seems to work fine, still.

Given that codeium.nvim is the only plugin on my machine that requires nui, and nui isn't even used anymore, it seemed a bit pointless to still have nui around. And *just* for the one-time authentication, one shouldn't have to add an extra dependency they potentially never need anymore.

Would it maybe make sense to remove the nui dependency and use `vim.notify` and `vim.ui.input` instead?

**Comment by jcdickinson** [comment]
Yeah, it would make sense. I wasn't aware of these when I wrote the auth code.
