### ISSUE TITLE
[bug] config file permission issue

### ISSUE THREAD

**Issue by towry** [jcdickinson/codeium.nvim#3]
<img width="615" alt="截屏2023-01-29 22 07 17" src="https://user-images.githubusercontent.com/8279858/215331719-21e4f14a-585e-4685-a286-0eab02589a65.png">

<img width="1045" alt="截屏2023-01-29 22 08 09" src="https://user-images.githubusercontent.com/8279858/215331747-ab859fd4-404d-49b9-b7d5-7f391e1b65e9.png">

<img width="381" alt="截屏2023-01-29 22 09 04" src="https://user-images.githubusercontent.com/8279858/215331800-40dc9c4d-e4fa-4794-8859-114d11c11e42.png">

**Comment by towry** [comment]
Maybe related to https://github.com/jcdickinson/codeium.nvim/issues/5, random guess.

**Comment by jcdickinson** [comment]
This is weird. What does `stat ~/.cache/nvim/codeium/config.json` give you? You can also override `config_path` in setup as a workaround.

**Comment by towry** [comment]
Another reading issue: 

```
Error detected while processing InsertEnter Autocommands for "*":                          
                                                                                            │Failed to load Codeium API key                                                             
                                                                                            │[codeium] [ERROR 08:56:59] ...owry/workspace/git-repos/codeium.nvim/lua/codeium/io.lua:94: 
                                                                                            │could not open  /Users/towry/.cache/nvim/codeium/config.json :  EACCES: permission denied: 
                                                                                            │/Users/towry/.cache/nvim/codeium/config.json  
```

**Comment by towry** [comment]
> This is weird. What does `stat ~/.cache/nvim/codeium/config.json` give you? You can also override `config_path` in setup as a workaround.

```
16777220 190157834 ---------x 1 towry staff 0 51 "Jan 30 08:56:33 2023" "Jan 30 08:56:28 202│                                                                                           
3" "Jan 30 08:56:28 2023" "Jan 30 08:56:28 2023" 4096 8 0 config.json 
```

**Comment by jcdickinson** [comment]
Totally my mistake, I created the file with permissions of `1`! You'll need to fix this by:

```sh
sudo chmod 666 $HOME/.cache/nvim/codeium/config.json
```

Please let me know if that works for you. My most recent commit addresses the issue.

**Comment by towry** [comment]
fixed.
