### ISSUE TITLE
recent fix borks win32 detection. 

### ISSUE THREAD

**Issue by WillEhrendreich** [jcdickinson/codeium.nvim#36]
@ww-daniel-mora 3a1f45b does not correctly resolve whether or not I'm running on windows. I've always seen the vim.fn.has("win32") in examples, and that works on my machine, so I'm curious what prompted the change to vim.call("exists","win32") == 1 . It comes up false for me.

**Comment by ww-daniel-mora** [comment]
@WillEhrendreich moot since "win32" does not show up on your machine either. But for your reference vim.fn has some off behavior. This discussion and the linked pr (rejected) inspired my first change  https://github.com/neovim/neovim/issues/19271.

**Comment by WillEhrendreich** [comment]
> @WillEhrendreich moot since "win32" does not show up on your machine either. But for your reference vim.fn has some odd behavior. This discussion and the linked pr (rejected) inspired my first change  https://github.com/neovim/neovim/issues/19271. 

Totally fine, I'm just glad it was resolved. =)
