### ISSUE TITLE
[Feature request] Add command to directly prompt for api key save

### ISSUE THREAD

**Issue by towry** [jcdickinson/codeium.nvim#4]

**Comment by jcdickinson** [comment]
So something like `:Codeium Auth <key>`?

**Comment by towry** [comment]
> So something like `:Codeium Auth <key>`?

Yes

**Comment by towry** [comment]
![截屏2023-01-30 09 19 02](https://user-images.githubusercontent.com/8279858/215368492-273223b9-54ac-4f37-a558-018a92ad3d40.png)

Thanks, great work.
