### ISSUE TITLE
This doesn't show multiline suggestions

### ISSUE THREAD

**Issue by TroySigX** [jcdickinson/codeium.nvim#40]
It need it to suggest the whole function (Codeium can do it), but this plugin only suggests 1 line at a time.

**Comment by zettlrobert** [comment]
@TroySigX

The plugin already provides completion suggestions, but you need to select one of them.

To enable this functionality, completion source has to be setup, as described in the readme.

In addition, you need to configure Neovim's completopt option accordingly. Assuming you have an options table that you iterate over, you can simply add the completeopt setting to it:

```lua
completeopt = {"menuone", "noselect", "preview"}
```

The preview option is what you need to accomplish your goal.

For more information on the completopt option, consult Neovim  documentation

```lua
:h 'completeopt'
```

![image](https://user-images.githubusercontent.com/19976985/229947688-000d11e9-630d-4035-aa51-90bd9419d804.png)

**Comment by TroySigX** [comment]
@zettlrobert I have set the `preview` option, but the issue still persists.

**Comment by TroySigX** [comment]
FYI, here's my config:
``` lua
vim.cmd([[set completeopt=menu,menuone,noselect,preview]])
require('codeium').setup({})
local has_words_before = function()
    unpack = unpack or table.unpack
    local line, col = unpack(vim.api.nvim_win_get_cursor(0))
    return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match('%s') == nil
end

local cmp = require('cmp')
cmp.setup({
    mapping = cmp.mapping.preset.insert({
    ['<C-Space>'] = cmp.mapping.complete{ reason = cmp.ContextReason.Auto },
    ['<C-e>'] = cmp.mapping.abort(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<Tab>'] = cmp.mapping(function(fallback)
        if not cmp.select_next_item() then
            if vim.bo.buftype ~= 'prompt' and has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end
    end, { 'i', 's' }),
    ['<S-Tab>'] = cmp.mapping(function(fallback)
        if not cmp.select_prev_item() then
            if vim.bo.buftype ~= 'prompt' and has_words_before() then
                cmp.complete()
            else
                fallback()
            end
        end
    end, { 'i', 's' }),
    }),

    sources = {
        { name = 'nvim_lsp' },
        { name = 'buffer' },
        { name = 'nvim_lsp_signature_help' },
        { name = 'luasnip' },
        { name = 'codeium' },
        -- { name = 'copilot' },
    },

    snippet = {
        expand = function(args)
            require('luasnip').lsp_expand(args.body)
        end,
    },
})

cmp.setup.cmdline('/', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
        { name = 'buffer' }
    }
})
``` 
Is there something that needs to be changed?

**Comment by zettlrobert** [comment]
I do not really see anything 'wrong' with your configuration, did you give the cmp wiki a look - https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#menu-type?

I still think you have an issue with your completeopt
please run the following and post the output:

```
:lua print(vim.inspect(vim.api.nvim_get_option_info("completeopt")))
```

**Comment by TroySigX** [comment]
Here's the output:
```
{
  allows_duplicates = false,
  commalist = true,
  default = "menu,preview",
  flaglist = false,
  global_local = false,
  last_set_chan = 0,
  last_set_linenr = 0,
  last_set_sid = 0,
  name = "completeopt",
  scope = "global",
  shortname = "cot",
  type = "string",
  was_set = false
}
```

**Comment by TroySigX** [comment]
Hmm, aside from formatting and additional mappings, you seem to have the exact config as me.

**Comment by jcdickinson** [comment]
Which version of nvim and which OS are you on?

**Comment by TroySigX** [comment]
I'm using nvim `0.8.3` and Endeavour OS kernel `6.2.9-arch1-1`

**Comment by jcdickinson** [comment]
Could you try install `neovim-git` from AUR? I'm pretty sure that multiline worked in 0.8, but I haven't used it in a while.

**Comment by TroySigX** [comment]
It still doesn't work

**Comment by zettlrobert** [comment]
> Hmm, aside from formatting and additional mappings, you seem to have the exact config as me.

Exactly, that's why i posted mine, could not think of a solution.
Sorry

**Comment by TroySigX** [comment]
Hi, any update on this? I recently updated to nvim `0.9.0`, but the issue still persists.

**Comment by TroySigX** [comment]
Hmm, it seems that in order to trigger `codeium`'s multiline suggestions, I need to write a lot of characters first. Here's my case, open a cpp file and type:
``` cpp
void sieve(){
}
```

In the function body, when typing `for` only (first thing to make a sieve):
``` cpp
void sieve(){
    for
}
```
 I would expect `codeium` to suggest the rest of the function, but in fact, it just suggested 1-line suggestion. But then I tried typing more characters, e.g `for(int `:
``` cpp
void sieve(){
    for(int 
}
````
It starts working properly and suggests multiline suggestions. Is there a way to fix it?
