### ISSUE TITLE
Incorrect system info detect for macOS

### ISSUE THREAD

**Issue by numbcoder** [jcdickinson/codeium.nvim#41]
https://github.com/jcdickinson/codeium.nvim/blob/84cc2022c6d118722c5a511ccb2d1e4cebc31fcf/lua/codeium/io.lua#L227
This line should be fixed with:
```lua
if os == "macos" and arch == "arm64" then
```

**Comment by jcdickinson** [comment]
Please let me know if this is now working for you.

**Comment by numbcoder** [comment]
Yes, It works well now. Thanks!
