### ISSUE TITLE
"Version of Codeium could not be determined"

### ISSUE THREAD

**Issue by chrisgrieser** [jcdickinson/codeium.nvim#45]
![CleanShot 2023-04-08 at 14 39 28@2x](https://user-images.githubusercontent.com/73286100/230721559-00094e96-05b6-4929-b012-29edbb1a3080.png)

this morning, it downloaded an codeium update and since then this warning occurs. codeium completions themselves do seem to work fine though

**Comment by jcdickinson** [comment]
This should be fixed, the `-stamp` arg to the language server was changed to `--stamp`.

**Comment by chrisgrieser** [comment]
thanks!

**Comment by Aman9das** [comment]
Im having the same error, any traceback possible?
