### ISSUE TITLE
What's the performance gain compared to `codeium.vim`?

### ISSUE THREAD

**Issue by nyngwang** [jcdickinson/codeium.nvim#53]
I'm using codeium.vim and thinking about migration, so curious about the performance profiling of the two.

**Comment by jcdickinson** [comment]
Performance improvements are always welcome as a PR, but the primary goal of this project is nvim-cmp integration. If you are interested about performance then do try out the http.nvim optional support (Linux and macos only) - which avoids having to exec curl.

Ultimately, performance profiles will be dominated by the latency between your machine and the Codeium servers. If you want maximum performance then consider self-hosting code completion with a GPU.
