### ISSUE TITLE
After unlocking nvim-cmp, updating, codeium gives off-by-one completion

### ISSUE THREAD

**Issue by Herob527** [jcdickinson/codeium.nvim#86]
So, I updated nvim-cmp (via lazy sync) which fixed codeium completions, but I'm getting off-by-one completions which aren't apparent in other sources

https://github.com/jcdickinson/codeium.nvim/assets/61355107/37510aba-01a3-48f2-95c0-e1619099561c

**Comment by cnfczn** [comment]
same problem

**Comment by caiyanhu** [comment]
same error

**Comment by rjshrjndrn** [comment]
Is this project maintained? I don't see any active commits apart from the bot.

**Comment by rjshrjndrn** [comment]
Seems like this commit causes the issue.
https://github.com/jcdickinson/codeium.nvim/commit/68e387cf96d53b2cfa325b44f2fae72a82e9f1a8
reverting to an older commit, solves the issue.
