### ISSUE TITLE
[bug]Duplicate completions

### ISSUE THREAD

**Issue by jinzhongjia** [jcdickinson/codeium.nvim#9]
I installed it according to the instructions, and there were multiple identical candidates when I completed it

![图片](https://user-images.githubusercontent.com/41784264/215375223-dddfa3a6-5bcf-4541-b528-2b433a8cccae.png)

**Comment by towry** [comment]
![截屏2023-01-30 10 42 59](https://user-images.githubusercontent.com/8279858/215376465-45e932a0-08cf-488f-990a-62fc4e8fcf7c.png)

Same issue.

**Comment by jinzhongjia** [comment]
And the completion is error, go no support ternary Conditional operator🤔

**Comment by jcdickinson** [comment]
Please give the latest commit a try.

> And the completion is error, go no support ternary Conditional operator

This is an unofficial plugin, this type of feedback is probably best provided to on the Codeium discord: https://discord.gg/3XFf78nAx5

**Comment by jinzhongjia** [comment]
now, it works great, thx
